### ISSUE TITLE
Is this plugin still compatible with recent versions of wordpress?  

### ISSUE THREAD

**Issue by sshojiro** [ARCommunications/Twitter-Cards-Meta#1]
#Basic info

PHP version: 5.3.29
WP version: missing (unfortunately, because some errors are raised now...)

#Bug occuring

My wordpress site dumps just the following message when `WP_DEBUG` in `wp-config.php` is enabled.

```php
Parse error: syntax error, unexpected '[' in /path/to/wordpress/wp-content/plugins/twitter-cards-meta/twcm-class-twitter-cards-preview.php on line 27
```

My question is the same with the issue title: `Is this plugin still compatible with recent versions of wordpress?  `

I'd very appreciate it if you may put some comment to this. Thank you in advance.

**Comment by rupok** [comment]
Hello @sshojiro 

It works fine. Looks like you are using PHP 5.4 or older which is not safe anymore and we dropped support for those older version. Make sure to update to PHP 5.6 at least.

Thanks!

**Comment by sshojiro** [comment]
Hi, @rupok 
Thank you for your quick response. I'll try to update the PHP version.
